### PR TITLE
Added support for creating vm with nested-virt

### PR DESCRIPTION
**Pull request by kbidarkar**
We are using snap-guest in sat6 . Would be nice to have nested-virt support added to snap-guest. :-)

### CODE REVIEW

**Comment by elyezer** [comment]
This will help create machines that will allow sat virtualization features do be tested.

**Comment by lzap** [comment]
Hey, thanks but I am afraid this will not copy the host parameters. According to your help text, I'd assume that `--cpu-feature` would do it, but as I read the patch, it should be `--cpu-feature=host`. Either change the default value and help, or change it to something more obvious please. I am totally fine if you statically add `--cpu=host` there, that will not hurt at all.

FYI I no longer use snap-guest, because virt-builder in Fedora 20+ is not in very usable state and I am able to build and spawn VMs very quickly. What I currently use is this:

https://github.com/lzap/bin-public/blob/master/fvb

I highly recommend virt-builder too, it works great even the plain version (my script only adds some sugar around it): http://libguestfs.org/virt-builder.1.html

**Comment by elyezer** [comment]
@lzap I think it is time to we consider updating/migrating to virt-builder too. Thanks for the comments.

**Comment by lzap** [comment]
> @lzap I think it is time to we consider updating/migrating to virt-builder too. Thanks for the comments.

Feel free to fix what I recommend here and I can merge your patch. I
find it confusing a little bit in this form.

## 

Later,
 Lukas #lzap Zapletal

**Comment by kbidarkar** [comment]
I agree with you lzap,
 the only reason why it is in the current state is to give an option to the user in case, the host cpu feature for the vm is not stable. In that case we can specify the required cpu model and features. 
Something like,

```
--cpu-feature core2duo,+x2apic "In case need a specific cpu type"
```

Adding statically would make snap-guest usage unstable on some older OS , so thought let me avoid it.

ok, I have reworded the help text now. hope it avoids confusion. :)

I had tested with "--cpu-feature host" and it worked. :)

Yeah, I think it would be better we move to virt-builder.

**Comment by lzap** [comment]
FYI "host" feature will copy all the features from your hypervisor. It's not necessary to play with individual options, you will get them all. Therefore I recommend you to make this default value:

```
CPU_FEATURE="--cpu=host"
```

**Comment by kbidarkar** [comment]
I am aware of that, but it may be unstable and hence do not want it as default.

I want nested_virt as an optional thing. If I add the default value, I believe every vm will get that feature. Which I think will make vm's unstable due to nested_virt on certain OS.

Not sure if I am missing something now.

**Comment by lzap** [comment]
Ok I am not aware of any unstability tho, I use this 10 times a day :-)

Merging thanks.

**Pull request merged**
